# Copyright (c) 2018 Pieter Hijma

# Permission is hereby granted, free of charge, to any person obtaining a 
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense, 
# and/or sell copies of the Software, and to permit persons to whom the 
# Software is furnished to do so, subject to the following conditions: 

# The above copyright notice and this permission notice shall be included in 
# all copies or substantial portions of the Software. 

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR 
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY, 
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL 
# THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER 
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING 
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER 
# DEALINGS IN THE SOFTWARE. 

#+property: header-args :comments link :tangle-mode (identity #o400) :results output silent :mkdirp yes

* Setting up the system

The following code shows how the system is defined.  For graphs, we rely on
~:cl-graph~ that needs ~:moptilities~ to provide extra functionality.

#+begin_src lisp :tangle "system/main/cl-graph-extension.asd"
(in-package :cl-user)

(defpackage :cl-graph-extension-asd
  (:use :cl :asdf))

(in-package :cl-graph-extension-asd)

(defsystem :cl-graph-extension
  :depends-on (:moptilities :cl-graph :simple-sets
			    ;; :alexandria
                            ;; :let-over-lambda
			       )
  :components ((:file "package")
	       (:file "cl-graph-extension"
		      :depends-on ("package"))))
#+end_src

#+begin_src lisp :tangle "system/main/package.lisp"
(in-package :cl-user)

(defpackage :cl-graph-extension
     (:use :cl :cl-graph :simple-sets
	   ;; :alexandria :lol
	   )
     ;;(:shadowing-import-from :alexandria :flatten)
     (:shadowing-import-from :simple-sets :union :set-difference :intersection)
     (:export :make-directed-graph
	      :graph=
	      :edge=
	      :closure))
#+end_src
